#! /bin/bash

sudo ln -sf $PWD/cameraClient.service /etc/systemd/system
sudo ln -sf $PWD/main.py /usr/bin/local/cameraClient

sudo systemctl daemon-reload
sudo systemctl enable cameraClient
sudo systemctl start cameraClient
