#! /bin/bash

sudo ln -sf $PWD/cameraClient /usr/bin/local/
sudo ln -sf $PWD/cameraClient.service /etc/systemd/system

sudo systemctl daemon-reload
sudo systemctl enable cameraClient
sudo systemctl start cameraClient
