#! /bin/bash

wget https://github.com/bluenviron/mediamtx/releases/download/v1.6.0/mediamtx_v1.6.0_linux_armv6.tar.gz

mkdir $PWD/mediamtx_armv6
tar -xf mediamtx_v1.6.0_linux_armv6.tar.gz -C $PWD/mediamtx_armv6

mv mediamtx_armv6/mediamtx .

rm -rf mediamtx_*

sudo l -sf $PWD/mediamtx /usr/local/bin/cameraStream
sudo ln -sf $PWD/cameraStream.service /etc/systemd/system

sudo systemctl daemon-reload
sudo systemctl enable cameraStream
sudo systemctl start cameraStream
